title: Topic

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          featuredImage:
            extends: fields/featuredImage
            help: The image that will be used as a fallback, if no posts are found.
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        label:
          en: Sub Topics
          de: Unterthemen
        empty:
          en: There are no sub topics yet.
          de: Es gibt noch keine Unterthemen.
        template: topic
      files: sections/files

